include: package:very_good_analysis/analysis_options.3.0.1.yaml
linter:
  rules:
    public_member_api_docs: false
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true